"""add longest_streak to user

Revision ID: 074b61265fa8
Revises: 114d04e241c6
Create Date: 2025-02-17 21:54:44.943974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074b61265fa8'
down_revision = '114d04e241c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longest_streak')

    # ### end Alembic commands ###
