"""add bookmark model

Revision ID: 114d04e241c6
Revises: a051c9f0b57e
Create Date: 2025-02-17 21:53:49.757017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114d04e241c6'
down_revision = 'a051c9f0b57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_url', sa.String(length=500), nullable=False),
    sa.Column('article_title', sa.String(length=200), nullable=True),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    # ### end Alembic commands ###
