"""Add global settings table

Revision ID: 3db8b6fc7571
Revises: b23bcedb7c9a
Create Date: 2025-03-26 18:56:38.130558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db8b6fc7571'
down_revision = 'b23bcedb7c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universal_theme', sa.String(length=50), nullable=True),
    sa.Column('set_by', sa.Integer(), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###
