"""Add reading mode preference

Revision ID: f1e839029ae5
Revises: e5c9bca079a9
Create Date: 2025-03-16 21:47:56.516129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e839029ae5'
down_revision = 'e5c9bca079a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_reading_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_reading_mode')

    # ### end Alembic commands ###
